# Generated by Django 3.0.8 on 2020-09-04 10:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(max_length=100, verbose_name='Texte')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('label', models.CharField(max_length=150, verbose_name='Intitulé de la convention')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'verbose_name': 'Convention',
                'verbose_name_plural': 'Conventions',
            },
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du groupe international')),
                ('link', models.URLField(verbose_name='Lien vers le groupe international')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, verbose_name='Lien de vers le details')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo')),
                ('title', models.CharField(max_length=100, verbose_name='Texte')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'verbose_name': 'Nomination',
                'verbose_name_plural': 'Nominations',
            },
        ),
        migrations.CreateModel(
            name='InterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'association")),
                ('filiere_promo', models.CharField(max_length=100, verbose_name='Filière(s) - Promotion(s)')),
                ('siege', models.CharField(max_length=100, verbose_name='Siège')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('members', models.ManyToManyField(blank=True, related_name='intergroups', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intergroup', to=settings.AUTH_USER_MODEL, verbose_name='Nom du président')),
            ],
            options={
                'verbose_name': 'Groupe international',
                'verbose_name_plural': 'Groupes internationaux',
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'association")),
                ('filiere_promo', models.CharField(max_length=100, verbose_name='Filière(s) - Promotion(s)')),
                ('siege', models.CharField(max_length=100, verbose_name='Siège')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('members', models.ManyToManyField(blank=True, related_name='associations', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='association', to=settings.AUTH_USER_MODEL, verbose_name='Répresentant')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
            },
        ),
    ]
