# Generated by Django 3.0.8 on 2020-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, verbose_name='Lien de vers le details')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
