# Generated by Django 3.0.8 on 2020-09-04 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='members_count',
        ),
        migrations.AddField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='associations', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
    ]
