# Generated by Django 3.0.8 on 2020-09-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknews',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
