# Generated by Django 3.0.8 on 2020-09-04 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0002_auto_20200904_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='association', to=settings.AUTH_USER_MODEL, verbose_name='Répresentant'),
        ),
        migrations.CreateModel(
            name='InterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'association")),
                ('filiere_promo', models.CharField(max_length=100, verbose_name='Filière(s) - Promotion(s)')),
                ('siege', models.CharField(max_length=100, verbose_name='Siège')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('members', models.ManyToManyField(blank=True, related_name='intergroups', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intergroup', to=settings.AUTH_USER_MODEL, verbose_name='Nom du président')),
            ],
            options={
                'verbose_name': 'Groupe international',
                'verbose_name_plural': 'Groupes internationaux',
            },
        ),
    ]
