# Generated by Django 3.0.8 on 2020-09-04 09:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200904_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
