# Generated by Django 3.0.8 on 2020-08-03 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Prenom')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière connexion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False, verbose_name='Membre')),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('photo', models.ImageField(blank=True, upload_to='photo/profiles/', verbose_name='Photo de profile')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birth_location', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('promo', models.CharField(blank=True, max_length=50, verbose_name='Promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
