# Generated by Django 3.0.8 on 2020-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200730_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Membre'),
        ),
    ]
