# Generated by Django 3.0.8 on 2020-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200902_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Feminin')], max_length=10, verbose_name='Sexe'),
        ),
    ]
