# Generated by Django 3.0.8 on 2020-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200731_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
