# Generated by Django 3.0.8 on 2020-09-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200902_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portrait_visible',
            field=models.BooleanField(default=True, verbose_name='Portrait visible'),
        ),
    ]
