# Generated by Django 3.0.8 on 2020-08-03 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/profiles/', verbose_name='Photo de profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Promotion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
