# Generated by Django 3.0.8 on 2020-09-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_portrait_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, max_length=50, verbose_name='Filière'),
        ),
    ]
