# Generated by Django 3.0.8 on 2020-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200906_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postes',
            field=models.TextField(blank=True, help_text='Renseigner sous le format (post, entreprise) séparer par un point-virgule(;)', verbose_name='Les postes precédements occupés et les entreprises respectives'),
        ),
    ]
