# Generated by Django 3.0.8 on 2020-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_postes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='in_ensai_year',
            field=models.CharField(blank=True, help_text='Exemple: 2002', max_length=10, null=True, verbose_name="Année d'entrée à l'ENSAI"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='out_ensai_year',
            field=models.CharField(blank=True, help_text='Exemple: 2005', max_length=10, null=True, verbose_name='Année de sortie'),
        ),
    ]
