# Generated by Django 3.0.8 on 2020-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200908_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entreprise_link',
            field=models.URLField(blank=True, verbose_name="Lien de l'entreprise"),
        ),
    ]
