# Generated by Django 3.0.8 on 2020-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_entreprise_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entreprise_link',
            field=models.URLField(blank=True, help_text='https://www.monentreprise.com', verbose_name="Lien de l'entreprise (url)"),
        ),
    ]
