# Generated by Django 3.0.8 on 2020-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('entreprise', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('label', models.CharField(max_length=150, verbose_name="Intitulé de l'offre")),
                ('description', models.TextField(verbose_name="Description de l'offre")),
                ('profil', models.TextField(help_text='Listez les profils separés par des virgules', verbose_name='Profil reherché')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom(s) et Prénom(s)')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('promotion', models.CharField(max_length=50, verbose_name='Promotion')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier de CV')),
            ],
            options={
                'verbose_name': 'Curriculum Vitae',
                'verbose_name_plural': 'Curriculums Vitaes',
            },
        ),
    ]
