# Generated by Django 3.0.8 on 2020-09-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contact_address',
            field=models.EmailField(default='aymar@gmail.com', help_text='Une adresse pour des éventuels postulats', max_length=254, verbose_name='Adresse de contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='website_url',
            field=models.URLField(blank=True, help_text='Lien vers un site web pour plus d\\informations', verbose_name='Référence'),
        ),
    ]
