# Generated by Django 3.0.8 on 2020-09-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriere', '0002_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curriculums Vitaes'},
        ),
    ]
