# Generated by Django 3.0.8 on 2020-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='school_out_date',
            field=models.CharField(blank=True, help_text='Exemple: 2014', max_length=8, verbose_name="Date de sortie de l'ENSAI"),
        ),
    ]
