# Generated by Django 3.0.8 on 2020-09-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200813_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', models.TextField(verbose_name='Texte')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'verbose_name': 'Projet industriel',
                'verbose_name_plural': 'Projets industriels',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', models.TextField(verbose_name='Texte')),
                ('file', models.FileField(upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'verbose_name': 'Projet institutionel',
                'verbose_name_plural': 'Projets institutionels',
            },
        ),
    ]
