# Generated by Django 3.0.8 on 2020-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200907_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialproject',
            name='content',
            field=models.TextField(verbose_name='Petite description du projet'),
        ),
        migrations.AlterField(
            model_name='industrialproject',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Joindre un document de projet'),
        ),
        migrations.AlterField(
            model_name='institutionalproject',
            name='content',
            field=models.TextField(verbose_name='Petite description du projet'),
        ),
        migrations.AlterField(
            model_name='institutionalproject',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Joindre un document de projet'),
        ),
    ]
