# Generated by Django 3.0.8 on 2020-07-27 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name="Nom de l'album")),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site ?')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'actualité")),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Image de couverture')),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site ?')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True)),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site ?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
            },
        ),
        migrations.CreateModel(
            name='GaleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('image', models.FileField(upload_to='gallery/')),
                ('galery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com.Galery', verbose_name='Album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
