# Generated by Django 3.0.8 on 2020-07-30 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date de la dernière modification'),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date de la dernière modification'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date de la dernière modification'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date de la dernière modification'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True)),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('start_time', models.TimeField(verbose_name='Heure de debut')),
                ('end_time', models.TimeField(verbose_name='Heure de Fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=50, verbose_name='Lieu')),
                ('location_city', models.CharField(default='Yaoundé', max_length=50, verbose_name='Ville')),
                ('expired', models.BooleanField(default=False, verbose_name='Expiré')),
                ('image_description', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d', verbose_name='Image de description')),
                ('published', models.BooleanField(default=True, verbose_name='Publier')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ManyToManyField(blank=True, related_name='register_events', to=settings.AUTH_USER_MODEL, verbose_name='Inscris')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
