# Generated by Django 3.0.8 on 2020-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='news', to='com.PostCategory'),
        ),
    ]
