# Generated by Django 3.0.8 on 2020-09-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Joindre un fichier'),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Joindre un fichier'),
        ),
    ]
