# Generated by Django 3.0.8 on 2020-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_auto_20200730_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Image de couverture'),
        ),
    ]
