# Generated by Django 3.0.8 on 2020-08-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image_description',
            new_name='image',
        ),
    ]
