# Generated by Django 3.0.8 on 2020-07-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_news_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryimage',
            name='galery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='com.Galery', verbose_name='Album'),
        ),
    ]
