# Generated by Django 3.0.8 on 2020-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_auto_20200813_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyComity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('object', models.CharField(max_length=100, verbose_name='Objet')),
                ('content', models.TextField(verbose_name='Messagé')),
            ],
            options={
                'verbose_name': 'Communiqué Comité Stratégique',
                'verbose_name_plural': 'Communiqué(s) Comité Stratégique',
            },
        ),
    ]
