# Generated by Django 3.0.8 on 2020-08-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0005_strategycomity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrategyComity',
            new_name='StrategicComity',
        ),
    ]
