# Generated by Django 3.0.8 on 2020-08-29 17:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0006_auto_20200819_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='strategiccomity',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
