# Generated by Django 3.0.8 on 2020-07-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0006_auto_20200731_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
