# Generated by Django 3.0.8 on 2020-08-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0007_auto_20200829_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('response', models.TextField(verbose_name='Reponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
