# Generated by Django 3.0.8 on 2020-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategiccomity',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Fichier joint'),
        ),
    ]
