# Generated by Django 3.0.8 on 2020-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicComity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=180, verbose_name="Titre à l'ADEN")),
                ('rule', models.CharField(max_length=150, verbose_name='Fonction ou Role')),
                ('location', models.CharField(max_length=150, verbose_name='Domicile')),
                ('promotion', models.CharField(max_length=80, verbose_name='Promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
