# Generated by Django 3.0.8 on 2020-09-04 10:44

import cloudinary.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', models.TextField(verbose_name='Contenu de a propos')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('title', models.CharField(blank=True, help_text='Ce champs est facultatif, à defaut le nom du fichier sera utilisé commme Intitulé', max_length=200, verbose_name='Intitulé ou petite description')),
                ('file', models.FileField(upload_to='', verbose_name="Fichier du plan d'action")),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'actions",
            },
        ),
        migrations.CreateModel(
            name='AdhesionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', models.TextField(help_text='Lister les conditions séparées par des virgules(,) exceptée la dernière !', verbose_name="Liste des conditions d'adhésion")),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Joindre un fichier')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue')),
            ],
            options={
                'verbose_name': "Condition d'adhésion",
                'verbose_name_plural': "Conditions d'adhésion",
            },
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue')),
            ],
            options={
                'verbose_name': 'Coordonnée',
                'verbose_name_plural': 'Coordonnées',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
                ('both_fr_en', models.BooleanField(verbose_name='Pour les deux langues ?')),
            ],
            options={
                'verbose_name': 'Filière et Formation',
                'verbose_name_plural': 'Filières et Formations',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('text', models.TextField(verbose_name='Texte')),
            ],
            options={
                'verbose_name': 'Pied de page',
                'verbose_name_plural': 'Pieds de page',
            },
        ),
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('description', models.TextField(verbose_name='Description du contenu')),
                ('date', models.DateField(blank=True, verbose_name='Assemblée générale du')),
                ('version', models.CharField(blank=True, choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'verbose_name': 'Assemblée Générale',
                'verbose_name_plural': 'Assemblées Générales',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
                ('both_fr_en', models.BooleanField(verbose_name='Pour les deux langues ?')),
            ],
            options={
                'verbose_name': 'Présentation institutionelle',
                'verbose_name_plural': 'Présentation institutionelles',
            },
        ),
        migrations.CreateModel(
            name='InternalRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Texte régit')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Joindre le fichier')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': 'Règlement interieur',
                'verbose_name_plural': 'Règlements interieurs',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=20, verbose_name='Nom du réseau social')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn')], max_length=10, verbose_name='Type du réseau')),
                ('accessibility', models.CharField(choices=[('private', 'Membre seulement'), ('public', 'Public')], default='public', max_length=10, verbose_name='Visibilité')),
                ('link', models.URLField(verbose_name='Lien direct du réseau social')),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Résaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Texte régit')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Joindre le fichier de statut')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': "Statut de l'association",
                'verbose_name_plural': "Statuts de l'association",
            },
        ),
        migrations.CreateModel(
            name='StrategicComity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=180, verbose_name="Titre à l'ADEN")),
                ('rule', models.CharField(max_length=150, verbose_name='Fonction ou Role')),
                ('location', models.CharField(max_length=150, verbose_name='Domicile')),
                ('promotion', models.CharField(max_length=80, verbose_name='Promotion')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo')),
                ('grade', models.CharField(choices=[('1', 'Niveau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3')], max_length=2, verbose_name='Priorité')),
            ],
            options={
                'verbose_name': 'Comité Stratégique',
                'verbose_name_plural': 'Comités Stratégiques',
            },
        ),
    ]
