# Generated by Django 3.0.8 on 2020-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategiccomity',
            options={'verbose_name': 'Comité Stratégique', 'verbose_name_plural': 'Comités Stratégiques'},
        ),
        migrations.AddField(
            model_name='strategiccomity',
            name='photo',
            field=models.ImageField(default='photo.png', upload_to='photos/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
