# Generated by Django 3.0.8 on 2020-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_auto_20200802_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('year', models.DateField(verbose_name="Année d'exécution")),
                ('file', models.FileField(upload_to='actions_plan/', verbose_name="Fichier du plan d'action")),
                ('language', models.CharField(choices=[('english', 'Anglaise'), ('french', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'actions",
            },
        ),
        migrations.CreateModel(
            name='InternalRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('file', models.FileField(upload_to='status/', verbose_name='Joindre le fichier')),
                ('language', models.CharField(choices=[('english', 'Anglaise'), ('french', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': 'Règlement interieur',
                'verbose_name_plural': 'Règlements interieurs',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('name', models.CharField(max_length=20, verbose_name='Nom du réseau social')),
                ('link', models.URLField(verbose_name='Lien direct du réseau social')),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Résaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('file', models.FileField(upload_to='status/', verbose_name='Joindre le fichier de statut')),
                ('language', models.CharField(choices=[('english', 'Anglaise'), ('french', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': "Statut de l'association",
                'verbose_name_plural': "Statuts de l'association",
            },
        ),
    ]
