# Generated by Django 3.0.8 on 2020-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_auto_20200905_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Joindre un fichier'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('envelope', 'Gmail')], max_length=10, verbose_name='Type du réseau'),
        ),
    ]
