# Generated by Django 3.0.8 on 2020-08-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_actionplan_internalregulation_socialnetwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='language',
            field=models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier'),
        ),
        migrations.AlterField(
            model_name='internalregulation',
            name='language',
            field=models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier'),
        ),
        migrations.AlterField(
            model_name='status',
            name='language',
            field=models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier'),
        ),
    ]
