# Generated by Django 3.0.8 on 2020-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_auto_20200806_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='accessibility',
            field=models.CharField(choices=[('private', 'Membre seulement'), ('public', 'Public')], default='public', max_length=10, verbose_name='Visibilité'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn')], default=1, max_length=10, verbose_name='Type du réseau'),
            preserve_default=False,
        ),
    ]
