# Generated by Django 3.0.8 on 2020-09-08 16:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Texte de la mention légale')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
