# Generated by Django 3.0.8 on 2020-09-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_legalmention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalmention',
            options={'verbose_name': 'Mentions Légales'},
        ),
    ]
