# Generated by Django 3.0.8 on 2020-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_auto_20200811_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', models.TextField(verbose_name='Contenu de a propos')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=10, verbose_name='Version de langue du fichier')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
    ]
