# Generated by Django 3.0.8 on 2020-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategiccomity',
            name='grade',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=1, max_length=2, verbose_name='Priorité'),
            preserve_default=False,
        ),
    ]
