# Generated by Django 3.0.8 on 2020-09-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0006_auto_20200908_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalmention',
            options={'verbose_name': 'Mention Légale', 'verbose_name_plural': 'Mentions Légales'},
        ),
    ]
