# Generated by Django 3.0.8 on 2020-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0007_strategiccomity_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategiccomity',
            name='grade',
            field=models.CharField(choices=[('1', 'Niveau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3')], max_length=2, verbose_name='Priorité'),
        ),
    ]
