# Generated by Django 3.0.8 on 2020-08-29 17:55

import cloudinary.models
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0008_auto_20200819_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplan',
            name='year',
        ),
        migrations.AddField(
            model_name='actionplan',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Texte régit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalregulation',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Texte régit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Texte régit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategiccomity',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo'),
        ),
    ]
