# Generated by Django 3.0.8 on 2020-09-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_auto_20200908_1722'),
        ('us', '0008_generalassembly_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalassembly',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='com.Galery', verbose_name='Joindre un album'),
        ),
    ]
