# Generated by Django 3.0.8 on 2020-08-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0010_auto_20200831_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('text', models.TextField(verbose_name='Texte')),
            ],
            options={
                'verbose_name': 'Pied de page',
                'verbose_name_plural': 'Pieds de page',
            },
        ),
    ]
