# Generated by Django 3.0.8 on 2020-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('description', models.TextField(verbose_name='Description du contenu')),
                ('date', models.DateField(blank=True, verbose_name='Assemblée générale du')),
                ('file_fr', models.FileField(blank=True, upload_to='', verbose_name='Version Française du fichier')),
                ('file_en', models.FileField(blank=True, upload_to='', verbose_name='Version Anglaise du fichier')),
            ],
            options={
                'verbose_name': 'Assemblée Générale',
                'verbose_name_plural': 'Assemblées Générales',
            },
        ),
    ]
