# Generated by Django 3.0.8 on 2020-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0012_generalassembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalassembly',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='generalassembly',
            name='file_fr',
        ),
        migrations.AddField(
            model_name='generalassembly',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Fichier joint'),
        ),
        migrations.AddField(
            model_name='generalassembly',
            name='version',
            field=models.CharField(blank=True, choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier'),
        ),
    ]
