# Generated by Django 3.0.8 on 2020-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0013_auto_20200903_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='content',
            field=models.TextField(blank=True, verbose_name='Intitulé ou petite description'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='file',
            field=models.FileField(upload_to='', verbose_name="Fichier du plan d'action"),
        ),
    ]
