# Generated by Django 3.0.8 on 2020-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0014_auto_20200903_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplan',
            name='content',
        ),
        migrations.AddField(
            model_name='actionplan',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Intitulé ou petite description'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='file',
            field=models.FileField(help_text='Ce champs est facultatif, à defaut le nom du fichier sera utilisé commme Intitulé', upload_to='', verbose_name="Fichier du plan d'action"),
        ),
    ]
