# Generated by Django 3.0.8 on 2020-09-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0017_c'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c',
            new_name='AdhesionCondition',
        ),
    ]
