# Generated by Django 3.0.8 on 2020-09-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0018_auto_20200903_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesioncondition',
            options={'verbose_name': "Condition d'adhésion", 'verbose_name_plural': "Conditions d'adhésion"},
        ),
    ]
