# Generated by Django 3.0.8 on 2020-09-03 18:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0019_auto_20200903_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
                ('both_fr_en', models.BooleanField(verbose_name='Pour les deux langues ?')),
            ],
            options={
                'verbose_name': 'Filière et Formation',
                'verbose_name_plural': 'Filières et Formations',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de la dernière modification')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('language', models.CharField(choices=[('en', 'Anglaise'), ('fr', 'Française')], max_length=3, verbose_name='Version de langue du fichier')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Fichier joint')),
                ('both_fr_en', models.BooleanField(verbose_name='Pour les deux langues ?')),
            ],
            options={
                'verbose_name': 'Présentation institutionelle',
                'verbose_name_plural': 'Présentation institutionelles',
            },
        ),
    ]
